# FILL IN THE MISSING VALUES BELOW
alerting:
  ???:
    token: "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" # WARN: DO NOT CHANGE THIS LINE
# FILL IN THE MISSING VALUES ABOVE

# FILL IN THE MISSING VALUES BELOW
endpoints:
  - name: Leantime
    url: lks-endpoint-leantime-600718600.us-east-1.elb.amazonaws.com # WARN: DO NOT CHANGE THIS LINE
    interval:
    conditions:
    alerts:
      - type: ???
        description: "Sensei, Leantime is down! Please check and fix it."

  - name: Gatus
    url: lks-endpoint-gatus-ul-363049383.us-east-1.elb.amazonaws.com # WARN: DO NOT CHANGE THIS LINE
    interval:
    conditions:
    alerts:
      - type: ???
        description: "Sensei, Gatus is down! Please check and fix it."
# FILL IN THE MISSING VALUES BELOW
